### PR TITLE
feat(ClanWar): add getMemberByMapPosition

### PR DESCRIPTION
**Pull request by ryancundiff**
Add method to ClanWar to provide encapsulated functionality for getting a member by their map position in war.

### CODE REVIEW

**Comment by csuvajit** [comment]
can you please bump the version as well?

**Comment by ryancundiff** [comment]
> can you please bump the version as well?

Done!

**Comment by csuvajit** [comment]
I would like to bring to your attention a slight inaccuracy in the mapPosition for CWL. When the team size is 30, but all 50 members were registered during the signup process, the mapPosition value exceeds 30.

**Comment by csuvajit** [comment]
The mapPosition is based on the registered member list for CWL

If you do `getMemberByMapPosition(10)`, it might return a wrong member or just null (if they were excluded from that round)

**Comment by ryancundiff** [comment]
> The mapPosition is based on the registered member list for CWL
> 
> If you do `getMemberByMapPosition(10)`, it might return a wrong member or just null (if they were excluded from that round)

How do you recommend I work around that? If it can return the wrong member then there is no way (that I can think of) to work around that. I could remove the functionality for CWL by passing ClanWar to the WarClan constructor and check the type and return null if it is equal to CWL. What do you think?

**Comment by csuvajit** [comment]
If you sort them by the mapPosition, the `index + 1` becomes the actual mapPosition.

**Comment by ryancundiff** [comment]
> However, I'm not sure if the members are already sorted by the mapPosition. I can comfirm that in 2-3 hours.

Did you confirm?

**Comment by csuvajit** [comment]
It is not sorted.

**Review by csuvajit — APPROVED** [review]

**Pull request merged**
